@baseUrl = http://localhost:3000/v1/consents
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNjA2MjU4MjUtNGJjNS00YjUzLWJlNmYtNzNkMDkwZjNmMzRiIiwiaWF0IjoxNjM4MTk0NzM4LCJleHAiOjE2MzgxOTU2MzgsImlzcyI6InN1cHBvcnRAZ3Jhbml0ZS5jb20iLCJqdGkiOiJmY2VjOGU3Yi00NzkzLTQ0MTktYWQwNC04OWYwYzllMGJiNGYifQ.4Bn8zC87C6JutvZPyFVXPkkQG456PXuoGHYj9d3F5X0

########################################################################
###########                       AUTH                       ###########
########################################################################

### Authenticates a user
POST {{baseUrl}}/auth/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "jane.doe@example.com",
  "password": "secret"
}

########################################################################
###########                      EVENT                       ###########
########################################################################

### Creates a new consent event for the authenticated user
POST {{baseUrl}}/events HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "email_notifications",
  "enabled": true
}

########################################################################
###########                      HEALTH                      ###########
########################################################################

### Get health status
GET {{baseUrl}}/health HTTP/1.1
Accept: application/json
Content-Type: application/json

########################################################################
###########                       USER                       ###########
########################################################################

### Get the authenticated user's profile
GET {{baseUrl}}/user HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Delete the authenticated user's account
DELETE {{baseUrl}}/user HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Register a new user
POST {{baseUrl}}/users/registration HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "alex.doe@example.com",
  "password": "secret"
}
