@baseUrl = http://localhost:3000/v1/consents
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiOWU5ZDNlY2EtYjIyNC00OGIwLTkwMTgtMDZkOTZjODhkZmQwIiwiaWF0IjoxNjM4Mjc2MTY1LCJleHAiOjE2MzgyNzcwNjUsImlzcyI6InN1cHBvcnRAZ3Jhbml0ZS5jb20iLCJqdGkiOiIwOTcwNTQ5YS05NmYwLTQ4OTQtYTc4Mi1kMjY1Y2JlYTA0MzMifQ.YNfQr5Ijt-HjXUJa9LjefK0BCyY9DzV5FUCVFGY3G9k

########################################################################
###########                       AUTH                       ###########
########################################################################

### Authenticates a user
POST {{baseUrl}}/auth/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "secret"
}

########################################################################
###########                      EVENT                       ###########
########################################################################

### Creates a new consent event for the authenticated user
POST {{baseUrl}}/events HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "email_notifications",
  "enabled": true
}

########################################################################
###########                      HEALTH                      ###########
########################################################################

### Get health status
GET {{baseUrl}}/health HTTP/1.1
Accept: application/json
Content-Type: application/json

########################################################################
###########                       USER                       ###########
########################################################################

### Get the authenticated user's profile
GET {{baseUrl}}/user HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Delete the authenticated user's account
DELETE {{baseUrl}}/user HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Register a new user
POST {{baseUrl}}/users/registration HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "secret"
}
