version: '3.8'

networks:
  development:
    driver: bridge

services:
  #########################
  ##      Backend        ##
  #########################

  svc-consents:
    image: granite-svc-consents:latest
    build:
      args:
        PACKAGE: svc-consents
      context: .
      dockerfile: packages/backend/Dockerfile
    env_file:
      - packages/backend/svc-consents/.env
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=3000
      - ENVIRONMENT=production
      - NODE_ENV=production
      - TYPEORM_DATABASE=granite
      - TYPEORM_HOST=db
      - TYPEORM_PASSWORD=masterkey
      - TYPEORM_PORT=5432
      - TYPEORM_SCHEMA=consents
      - TYPEORM_USERNAME=granite
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - development
    container_name: svc-consents

  #########################
  ##     Persistence     ##
  #########################

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=granite
      - POSTGRES_PASSWORD=masterkey
      - POSTGRES_USER=granite
    ports:
      - 5432:5432
    networks:
      - development
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
    container_name: granite-db

  db-integration:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=granite
      - POSTGRES_PASSWORD=masterkey
      - POSTGRES_USER=granite
    ports:
      - 5433:5432
    networks:
      - development
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
    container_name: granite-db-integration
