version: '3.8'

networks:
  development:
    driver: bridge

services:
  #########################
  ##      Backend        ##
  #########################

  svc-consents:
    build:
      args:
        APP: svc-consents
      context: .
      dockerfile: packages/backend/Dockerfile
    env_file:
      - packages/backend/svc-consents/.env
    ports:
      - 3001:3000
    networks:
      - development
    container_name: svc-consents

  #########################
  ##     Persistence     ##
  #########################

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=granite
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=granite
    ports:
      - 5432:5432
    networks:
      - development
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
    container_name: granite-db

  db-integration:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=granite
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=granite
    ports:
      - 5433:5432
    networks:
      - development
    container_name: granite-db-integration

  redis:
    image: redis:6-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - development
    container_name: granite-redis

  redis-integration:
    image: redis:6-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6380:6379
    networks:
      - development
    container_name: granite-redis-integration
