name: backend.svc-consents

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/backend.svc-consents.yaml
      - packages/backend/svc-consents/**
      - packages/backend/tsconfig-backend.json
      - package.json
      - tsconfig.json
      - types/**/*.ts
      - '!**.md'
      - '!**/.gitignore'
  pull_request:
    paths:
      - .github/workflows/backend.svc-consents.yaml
      - packages/backend/svc-consents/**
      - packages/backend/tsconfig-backend.json
      - package.json
      - tsconfig.json
      - types/**/*.ts
      - '!**.md'
      - '!**/.gitignore'
  workflow_dispatch: null

env:
  PACKAGE: 'svc-consents'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@master
      - name: Install node
        uses: actions/setup-node@master
        with:
          node-version: 16.x
      - name: Install yarn
        run: yarn install --immutable
      - name: Build package
        run: yarn workspace $PACKAGE build
      - name: Lint package
        run: yarn workspace $PACKAGE lint
  test_unit:
    name: Test Unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@master
      - name: Install node
        uses: actions/setup-node@master
        with:
          node-version: 16.x
      - name: Install yarn
        run: yarn install --immutable
      - name: Run package unit tests
        run: yarn workspace $PACKAGE test:unit
  test_integration:
    name: Test Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@master
      - name: Install node
        uses: actions/setup-node@master
        with:
          node-version: 16.x
      - name: Install yarn
        run: yarn install --immutable
      - name: Run package integration tests
        run: yarn workspace $PACKAGE test:integration
