name: publish
on:
  release:
    types: [published]

jobs:
  docker:
    name: docker build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: nicolaspearson
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push latest version
        uses: docker/build-push-action@master
        with:
          build-args: |
            GITHUB_SHA=${{ github.sha }}
            VERSION=${{ steps.vars.outputs.version }}
            PACKAGE=${{ github.event.deployment.payload.package }}
          cache-from: type=registry,ref=ghcr.io/nicolaspearson/${{ github.event.deployment.payload.package }}
          cache-to: type=inline
          context: ${{ github.event.deployment.payload.docker.context }}
          file: ${{ github.event.deployment.payload.docker.file }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/nicolaspearson/${{ github.event.deployment.payload.package }}:latest
            ghcr.io/nicolaspearson/${{ github.event.deployment.payload.package }}:${{ steps.vars.outputs.version }}
            ghcr.io/nicolaspearson/${{ github.event.deployment.payload.package }}:${{ github.sha }}
